### ISSUE TITLE
pex reactor fixes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-p2p#9]
See TODO's in pex_reactor.go.

Namely, remove peers, prevent abuse, improve some logic.

**Comment by jaekwon** [comment]
The addrbook was taken from conformal/BTCD, so updates might be incorporated from there too.

**Comment by akalyaev** [comment]
@ebuchman is the simple counter ("not more than 1000 messages per hour") enough to prevent abuse?

**Comment by akalyaev** [comment]
Implemented a simple counter per peer.
